CREATE TABLE public.agent_workers (
  id text PRIMARY KEY,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'offline'
    CHECK (status IN ('online', 'busy', 'offline', 'error')),
  capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_heartbeat_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agent_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  prompt text NOT NULL,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN (
      'queued',
      'running',
      'awaiting_approval',
      'completed',
      'failed',
      'stalled',
      'canceled'
    )),
  progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  current_step text,
  risk_class text NOT NULL DEFAULT 'internal_owned'
    CHECK (risk_class IN (
      'internal_owned',
      'financial',
      'live_security',
      'destructive',
      'external'
    )),
  requires_approval boolean NOT NULL DEFAULT false,
  approval_state text NOT NULL DEFAULT 'not_required'
    CHECK (approval_state IN ('not_required', 'pending', 'approved', 'rejected')),
  worker_id text REFERENCES public.agent_workers(id) ON DELETE SET NULL,
  plan jsonb NOT NULL DEFAULT '[]'::jsonb,
  result jsonb,
  error_message text,
  last_heartbeat_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agent_task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id uuid NOT NULL REFERENCES public.agent_tasks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  status text,
  step text,
  message text NOT NULL,
  progress integer CHECK (progress IS NULL OR progress BETWEEN 0 AND 100),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agent_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_id text NOT NULL UNIQUE,
  task_id uuid NOT NULL REFERENCES public.agent_tasks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL,
  summary text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX agent_tasks_user_created_idx
  ON public.agent_tasks (user_id, created_at DESC);
CREATE INDEX agent_tasks_status_created_idx
  ON public.agent_tasks (status, created_at);
CREATE INDEX agent_task_events_task_created_idx
  ON public.agent_task_events (task_id, created_at);
CREATE INDEX agent_receipts_task_created_idx
  ON public.agent_receipts (task_id, created_at);

ALTER TABLE public.agent_workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_task_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_receipts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users can read their agent tasks"
ON public.agent_tasks FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "users can read their agent task events"
ON public.agent_task_events FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "users can read their agent receipts"
ON public.agent_receipts FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.set_agent_runtime_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER agent_workers_set_updated_at
BEFORE UPDATE ON public.agent_workers
FOR EACH ROW EXECUTE FUNCTION public.set_agent_runtime_updated_at();

CREATE TRIGGER agent_tasks_set_updated_at
BEFORE UPDATE ON public.agent_tasks
FOR EACH ROW EXECUTE FUNCTION public.set_agent_runtime_updated_at();

ALTER PUBLICATION supabase_realtime ADD TABLE public.agent_tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.agent_task_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.agent_receipts;
